#!/usr/bin/env node

/**
 * Инициализация модулей.
 */

var app = require('../app');
var debug = require('debug')('autoshop:server');
var http = require('http');
var config = require('../app/config');


/**
 * Get port from environment and store in Express. Получения порта из окружения или установления порта 3000 и присвоения этого порта вприлодению
 */

//var port = normalizePort(process.env.PORT || '3000');
app.set('port', config.server.port);

var server = http.createServer(app);//Создние HTTP сервера для приложения

/**
 * Listen on provided port, on all network interfaces. Устанавливаем прослушивания выбранного порта для нашего веб-сервера на всех интерфейсах
 */

server.listen(process.env.PORT || config.server.port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.


function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}
 */

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
